# Generated by Django 3.2 on 2021-06-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='switch',
            new_name='switch1',
        ),
        migrations.AddField(
            model_name='thing',
            name='switch2',
            field=models.BooleanField(default=False),
        ),
    ]
